services:
  # Service web pour l'application Node.js
  - type: web
    name: aci-online
    env: node
    buildCommand: npm install && npm run db:generate && npm run build && npm run db:init
    startCommand: npm run start
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - vite.config.ts
        - postcss.config.js
        - tailwind.config.ts
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aci-online-db
          property: connectionString

# Configuration de la base de données PostgreSQL
databases:
  - name: aci-online-db
    plan: starter
